/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'stars': MotiaStream<{ stars: number; name: string; fullName: string; organization: string; lastUpdated: string }>
  }

  interface Handlers {
    'GitHubStarWebhook': ApiRouteHandler<{ action: 'created' | 'deleted'; starred_at?: string; repository: { name: string; full_name: string; stargazers_count: number; owner: { login: string } }; sender: { login: string; name: string; avatar_url?: string } }, ApiResponse<200, { message: string; event: string; processed: boolean }> | ApiResponse<400, { error: string }> | ApiResponse<401, { error: string }> | ApiResponse<500, { error: string }>, never>
  }
}